import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { io } from "socket.io-client";
import { PrismaClient } from "@prisma/client";
import { CRYPTO_VERSION } from "../src/lib/crypto/constants";
import { decryptFileChunks, encryptFileChunks } from "../src/lib/crypto/file";
import { decryptJson, encryptJson, parseEnvelope } from "../src/lib/crypto/payload";
import { generateRoomKey, importRoomKey } from "../src/lib/crypto/room-key";

const base = "http://localhost:3000"; const db = new PrismaClient(); let slug = "";
const wait = <T>(socket: ReturnType<typeof io>, event: string, predicate: (value: T) => boolean, timeout = 7000) => new Promise<T>((resolve, reject) => { const timer = setTimeout(() => reject(new Error(`Timeout: ${event}`)), timeout); const handler = (value: T) => { if (predicate(value)) { clearTimeout(timer); socket.off(event, handler); resolve(value); } }; socket.on(event, handler); });
try {
  const serializedKey = generateRoomKey(), keyA = await importRoomKey(serializedKey), keyB = await importRoomKey(serializedKey); const created = await fetch(`${base}/api/rooms`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ttlHours: 1 }) }); assert.equal(created.status, 200); ({ slug } = await created.json() as { slug: string }); const ownerCookie = created.headers.getSetCookie().map((value) => value.split(";")[0]).join("; "); const encryptedVerifier = JSON.stringify(await encryptJson(keyA, { check: "blinkroom-room-key" }, `${slug}:verifier:v1`)); const verifierResponse = await fetch(`${base}/api/rooms/${slug}/verifier`, { method: "POST", headers: { "content-type": "application/json", cookie: ownerCookie }, body: JSON.stringify({ encryptionVersion: 1, encryptedVerifier }) }); assert.equal(verifierResponse.status, 200);
  const a = io(base, { path: "/api/socket" }), b = io(base, { path: "/api/socket" }); const aid = crypto.randomUUID(), bid = crypto.randomUUID(); await Promise.all([new Promise<void>((resolve) => a.on("connect", resolve)), new Promise<void>((resolve) => b.on("connect", resolve))]); a.emit("room:join", { slug, participantId: aid, name: "Room owner" }); await wait(a, "presence:update", (value: unknown[]) => value.length === 1); b.emit("room:join", { slug, participantId: bid, name: "Guest" }); await wait(a, "presence:update", (value: unknown[]) => value.length === 2);
  const message = "secret message", textId = crypto.randomUUID(); const encryptedPayload = JSON.stringify(await encryptJson(keyA, { content: message, senderName: "Room owner" }, `${slug}:${textId}:content:v1`)); const requestBody = JSON.stringify({ itemId: textId, senderId: aid, type: "TEXT", encryptionVersion: CRYPTO_VERSION, encryptedPayload }); assert.ok(!requestBody.includes(message)); const textEvent = wait<{ id: string; encryptedPayload: string }>(b, "item:create", (item) => item.id === textId); const textResponse = await fetch(`${base}/api/rooms/${slug}/items/text`, { method: "POST", headers: { "content-type": "application/json" }, body: requestBody }); assert.equal(textResponse.status, 201); const relayed = await textEvent; assert.ok(!JSON.stringify(relayed).includes(message)); const unlocked = await decryptJson<{ content: string }>(keyB, parseEnvelope(relayed.encryptedPayload), `${slug}:${textId}:content:v1`); assert.equal(unlocked.content, message);
  const filename = "secret-document.pdf", filePlaintext = new TextEncoder().encode("confidential pdf bytes"), fileId = crypto.randomUUID(); const encryptedMetadata = JSON.stringify(await encryptJson(keyA, { fileName: filename, mimeType: "application/pdf", fileSize: filePlaintext.byteLength, senderName: "Guest 1" }, `${slug}:${fileId}:metadata:v1`)); assert.ok(!encryptedMetadata.includes(filename)); const encryptedBlob = await encryptFileChunks(keyA, new Blob([filePlaintext]), slug, fileId); const form = new FormData(); form.append("itemId", fileId); form.append("senderId", bid); form.append("type", "FILE"); form.append("encryptionVersion", "1"); form.append("encryptedMetadata", encryptedMetadata); form.append("file", encryptedBlob, "encrypted.bin"); const fileEvent = wait<{ id: string; encryptedMetadata: string }>(a, "item:create", (item) => item.id === fileId); const upload = await fetch(`${base}/api/rooms/${slug}/items/upload`, { method: "POST", body: form }); assert.equal(upload.status, 201); await fileEvent;
  const stored = await db.roomItem.findUniqueOrThrow({ where: { id: fileId } }); assert.ok(stored.storageKey); const disk = await readFile(`storage/${stored.storageKey}`); assert.equal(disk.includes(Buffer.from(filePlaintext)), false); assert.equal(disk.includes(Buffer.from(filename)), false); const source = await fetch(`${base}/api/rooms/${slug}/items/${fileId}/download`); assert.equal(source.status, 200); const { url } = await source.json() as { url: string }; assert.match(url, /^\/api\/files\//); const download = await fetch(new URL(url, base)); assert.equal(download.status, 200); assert.equal(download.headers.get("content-type"), "application/octet-stream"); assert.equal(download.headers.get("content-disposition"), "attachment; filename=encrypted.bin"); const decrypted = await decryptFileChunks(keyB, await download.blob(), slug, fileId, "application/pdf"); assert.deepEqual(new Uint8Array(await decrypted.arrayBuffer()), filePlaintext);
  const destroyedA = wait(a, "room:destroy", () => true), destroyedB = wait(b, "room:destroy", () => true); const destroyed = await fetch(`${base}/api/rooms/${slug}`, { method: "DELETE", headers: { cookie: ownerCookie } }); assert.equal(destroyed.status, 200); await Promise.all([destroyedA, destroyedB]); a.close(); b.close(); console.log(JSON.stringify({ fragmentKeyNeverSent: true, plaintextAbsentFromTextRequestAndEvent: true, encryptedStorage: true, clientDownloadDecrypts: true, destroyRealtime: true }));
} finally { if (slug) await db.room.deleteMany({ where: { slug } }); await db.$disconnect(); }
