import assert from "node:assert/strict";
import { io } from "socket.io-client";
import { encryptFileChunks } from "../src/lib/crypto/file";
import { encryptJson } from "../src/lib/crypto/payload";
import { generateRoomKey, importRoomKey } from "../src/lib/crypto/room-key";

const base = process.env.TEST_BASE_URL ?? "http://localhost:3000";
async function createRoom() { const response = await fetch(`${base}/api/rooms`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ttlHours: 1 }) }); assert.equal(response.status, 200); const cookie = response.headers.get("set-cookie")?.split(";")[0] ?? ""; return { ...await response.json() as { slug: string }, cookie }; }
const once = <T>(socket: ReturnType<typeof io>, event: string, timeout = 3000) => new Promise<T>((resolve, reject) => { const timer = setTimeout(() => reject(new Error(`Timed out: ${event}`)), timeout); socket.once(event, (value: T) => { clearTimeout(timer); resolve(value); }); });

const a = await createRoom(), b = await createRoom(); const roomKey = await importRoomKey(generateRoomKey()); const itemId = crypto.randomUUID(); const senderId = crypto.randomUUID(); const metadata = JSON.stringify(await encryptJson(roomKey, { fileName: "direct-secret.bin", mimeType: "application/octet-stream", fileSize: 1024, senderName: "Room owner" }, `${a.slug}:${itemId}:metadata:v1`)); const encrypted = await encryptFileChunks(roomKey, new Blob([new Uint8Array(1024)]), a.slug, itemId);
const direct = await fetch(`${base}/api/rooms/${a.slug}/items/direct`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId, senderId, type: "FILE", encryptionVersion: 1, encryptedMetadata: metadata, encryptedSize: encrypted.size }) }); assert.equal(direct.status, 201); const directItem = await direct.json() as { availability: string }; assert.equal(directItem.availability, "DIRECT"); assert.equal((await fetch(`${base}/api/files/${a.slug}/${itemId}`)).status, 404);

const socketA = io(base, { path: "/api/socket", transports: ["websocket"] }); const socketB = io(base, { path: "/api/socket", transports: ["websocket"] }); const participantA = crypto.randomUUID(), participantB = crypto.randomUUID(); await Promise.all([once(socketA, "connect"), once(socketB, "connect")]); socketA.emit("room:join", { slug: a.slug, participantId: participantA, name: "Guest" }); socketB.emit("room:join", { slug: b.slug, participantId: participantB, name: "Guest" }); await new Promise((resolve) => setTimeout(resolve, 100)); let crossed = false; socketB.once("webrtc:offer", () => { crossed = true; }); socketA.emit("webrtc:offer", { target: participantB, description: { type: "offer", sdp: "v=0\r\n" } }); await new Promise((resolve) => setTimeout(resolve, 350)); assert.equal(crossed, false);

const socketC = io(base, { path: "/api/socket", transports: ["websocket"] }); const participantC = crypto.randomUUID(); await once(socketC, "connect"); socketC.emit("room:join", { slug: a.slug, participantId: participantC, name: "Guest" }); await new Promise((resolve) => setTimeout(resolve, 100)); const offerPromise = once<{ from: string; description: { sdp: string }; roomKey?: string }>(socketC, "webrtc:offer"); socketA.emit("webrtc:offer", { target: participantC, description: { type: "offer", sdp: "v=0\r\n" } }); const offer = await offerPromise; assert.equal(offer.from, participantA); assert.equal(offer.description.sdp, "v=0\r\n"); assert.equal(offer.roomKey, undefined);
socketA.disconnect(); socketB.disconnect(); socketC.disconnect(); await fetch(`${base}/api/rooms/${a.slug}`, { method: "DELETE", headers: { Cookie: a.cookie } }); await fetch(`${base}/api/rooms/${b.slug}`, { method: "DELETE", headers: { Cookie: b.cookie } });
console.log(JSON.stringify({ directItemHasNoStorageBlob: true, crossRoomSignalingRejected: true, sameRoomSignalingRelayed: true, signalingContainsNoRoomKey: true }));
