import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/src/lib/db";
import { tokenHash } from "@/src/lib/security";
import { roomChannel } from "@/src/server/realtime";
import { storage } from "@/src/server/storage";
const completeSchema = z.object({ parts: z.array(z.object({ partNumber: z.number().int().min(1).max(10_000), etag: z.string().min(1).max(512) }).strict()).min(1).max(10_000) }).strict();
type Ctx = { params: Promise<{ slug: string; sessionId: string }> };
export async function POST(req: NextRequest, { params }: Ctx) { const { slug, sessionId } = await params; const input = completeSchema.safeParse(await req.json().catch(() => null)); if (!input.success) return NextResponse.json({ error: "Invalid upload completion" }, { status: 400 }); const session = await db.uploadSession.findFirst({ where: { id: sessionId, room: { slug }, status: "UPLOADING" }, include: { room: true } }); if (!session || tokenHash(req.headers.get("x-upload-token") ?? "") !== session.uploadTokenHash) return NextResponse.json({ error: "Upload unavailable" }, { status: 403 }); if (session.room.status !== "ACTIVE" || session.room.expiresAt <= new Date() || !session.multipartUploadId) return NextResponse.json({ error: "Upload unavailable" }, { status: 410 }); try { const ordered = [...input.data.parts].sort((a, b) => a.partNumber - b.partNumber); if (ordered.some((part, index) => part.partNumber !== index + 1)) return NextResponse.json({ error: "Missing upload part" }, { status: 400 }); await storage.completeMultipartUpload(session.storageKey, session.multipartUploadId, ordered); if (await storage.headSize(session.storageKey) !== Number(session.encryptedSize)) { await storage.delete(session.storageKey); await db.uploadSession.update({ where: { id: session.id }, data: { status: "FAILED" } }); return NextResponse.json({ error: "Encrypted upload size mismatch" }, { status: 400 }); }
    const item = await db.$transaction(async (tx) => { const created = await tx.roomItem.create({ data: { id: session.itemId, roomId: session.roomId, senderId: session.senderId, type: session.itemType, encryptedMetadata: session.encryptedMetadata, encryptionVersion: 1, encryptedSize: Number(session.encryptedSize), storageKey: session.storageKey, availability: session.directDelivered ? "HYBRID" : "STORED" } }); await tx.uploadSession.update({ where: { id: session.id }, data: { status: "COMPLETED", completedAt: new Date() } }); return created; }); const output = { id: item.id, senderId: item.senderId, type: item.type, encryptedPayload: null, encryptedMetadata: item.encryptedMetadata, encryptionVersion: item.encryptionVersion, encryptedSize: item.encryptedSize, availability: item.availability, createdAt: item.createdAt.toISOString() }; roomChannel.itemCreated(slug, output); return NextResponse.json(output);
  } catch { await db.uploadSession.updateMany({ where: { id: session.id, status: "UPLOADING" }, data: { status: "FAILED" } }); return NextResponse.json({ error: "Temporary storage is unavailable right now." }, { status: 503 }); } }
export async function DELETE(req: NextRequest, { params }: Ctx) { const { slug, sessionId } = await params; const session = await db.uploadSession.findFirst({ where: { id: sessionId, room: { slug }, status: { in: ["PENDING", "UPLOADING", "FAILED"] } } }); if (!session) return NextResponse.json({ ok: true }); if (tokenHash(req.headers.get("x-upload-token") ?? "") !== session.uploadTokenHash) return NextResponse.json({ error: "Upload unavailable" }, { status: 403 }); if (session.multipartUploadId) await storage.abortMultipartUpload(session.storageKey, session.multipartUploadId); await storage.delete(session.storageKey).catch(() => undefined); await db.uploadSession.update({ where: { id: session.id }, data: { status: "ABORTED" } }); return NextResponse.json({ ok: true }); }
