"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
type Range = "24h" | "7d" | "30d" | "all";
type Metric = "visits" | "roomsCreated" | "filesUploaded" | "filesDownloaded";
type Data = {
  collectedFrom: string | null; hasComparison: boolean;
  summary: { visits:number; pageViews:number; roomsCreated:number; activeRooms:number; filesUploaded:number; filesDownloaded:number; uploadBytes:string; downloadBytes:string; averageFileSize:string; failedUploads:number; failedDownloads:number; conversionRate:number };
  comparison: Record<string,number>; timeline:Array<{timestamp:string;visits:number;pageViews:number;roomsCreated:number;filesUploaded:number;filesDownloaded:number}>;
  funnel:Array<{label:string;value:number}>; rooms:{averageLifetimeMs:number;averageFilesPerRoom:number;averageDownloadsPerRoom:number;expiredRooms:number;destroyedRooms:number;activeRooms:number};
  files:{averageFileSize:string;largestFile:string;totalFiles:number;averageDownloadsPerFile:number;uploadBytes:string;downloadBytes:string;distribution:Record<string,number>};
  devices:{device:Record<string,number>;browser:Record<string,number>}; recentActivity:Array<{event:string;timestamp:string}>;
  health:{uploadSuccessRate:number;downloadSuccessRate:number;failedUploads:number;failedDownloads:number;averageUploadDurationMs:number;transferVolume:string};
};
const ranges:Array<[Range,string]> = [["24h","24 Hours"],["7d","7 Days"],["30d","30 Days"],["all","All Time"]];
const metricOptions:Array<[Metric,string]> = [["visits","Visits"],["roomsCreated","Rooms Created"],["filesUploaded","Uploads"],["filesDownloaded","Downloads"]];
function bytes(value:string){let amount=Number(value),unit="B";for(const next of ["KB","MB","GB","TB","PB"]){if(amount<1024)break;amount/=1024;unit=next}return `${amount>=100||unit==="B"?amount.toFixed(0):amount>=10?amount.toFixed(1):amount.toFixed(2)} ${unit}`}
const number=(value:number,digits=1)=>new Intl.NumberFormat("en",{maximumFractionDigits:digits}).format(value);
function duration(ms:number){if(!ms)return "—";const hours=ms/3_600_000;if(hours>=24)return `${number(hours/24)} days`;if(hours>=1)return `${number(hours)} hrs`;return `${number(ms/60_000)} min`}
function Change({value,range}:{value:number;range:Range}){if(range==="all")return <small className="metric-change neutral">All-time total</small>;const label=range==="24h"?"24 hours":range==="7d"?"7 days":"30 days";return <small className={`metric-change ${value>0?"up":value<0?"down":"neutral"}`}>{value>0?"+":""}{number(value)}% vs previous {label}</small>}
function SectionTitle({label,title,detail}:{label:string;title:string;detail?:string}){return <header className="section-title"><div><span>{label}</span><h2>{title}</h2></div>{detail&&<small>{detail}</small>}</header>}
function StatGrid({items}:{items:Array<[string,string|number]>}){return <div className="analytics-stat-grid">{items.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}
function Distribution({values}:{values:Record<string,number>}){const total=Math.max(1,Object.values(values).reduce((a,b)=>a+b,0));return <div className="distribution">{Object.entries(values).map(([label,value])=><div key={label}><span>{label}<b>{number(value,0)}</b></span><i><b style={{width:`${value/total*100}%`}}/></i></div>)}</div>}
export function AnalyticsDashboard(){
  const [range,setRange]=useState<Range>("7d"),[metric,setMetric]=useState<Metric>("visits"),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[unauthorized,setUnauthorized]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{await Promise.resolve();setLoading(true);setError("");try{const res=await fetch(`/api/admin/analytics?range=${range}`,{cache:"no-store"});if(res.status===401){setUnauthorized(true);setData(null);return}if(!res.ok)throw new Error();setData(await res.json());setUnauthorized(false)}catch{setError("Metrics could not be loaded.")}finally{setLoading(false)}},[range]);
  // Synchronize the selected global range with the server aggregation source.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  async function login(form:FormData){setError("");const res=await fetch("/api/admin/analytics/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:form.get("token")})});if(!res.ok){setError("Invalid admin token.");return}await load()}
  const chart=useMemo(()=>{const values=data?.timeline.map(p=>p[metric])??[],max=Math.max(1,...values),width=1000,height=220;return values.map((value,index)=>`${values.length===1?width/2:index/(values.length-1)*width},${height-value/max*(height-8)}`).join(" ")},[data,metric]);
  if(unauthorized)return <main className="analytics-shell"><section className="analytics-login"><Link className="wordmark" href="/">BlinkRoom<i/></Link><p>PRIVATE METRICS</p><h1>BlinkRoom Analytics</h1><form action={login}><label htmlFor="token">Admin token</label><input id="token" name="token" type="password" autoComplete="current-password" required/><button className="button filled">Continue</button></form>{error&&<span className="analytics-error">{error}</span>}</section></main>;
  const s=data?.summary,cards=s?[{label:"VISITS",value:number(s.visits,0),key:"sessions"},{label:"ROOMS CREATED",value:number(s.roomsCreated,0),key:"roomsCreated"},{label:"ACTIVE ROOMS",value:number(s.activeRooms,0)},{label:"FILES UPLOADED",value:number(s.filesUploaded,0),key:"filesUploaded"},{label:"DOWNLOADS",value:number(s.filesDownloaded,0),key:"filesDownloaded"},{label:"DATA UPLOADED",value:bytes(s.uploadBytes),key:"uploadBytes"},{label:"DATA DOWNLOADED",value:bytes(s.downloadBytes),key:"downloadBytes"},{label:"CONVERSION",value:`${number(s.conversionRate)}%`}] : [];
  return <main className="analytics-shell"><header><Link className="wordmark" href="/">BlinkRoom<i/></Link><span>Privacy-first · Aggregate only · UTC</span></header><section className="analytics-main"><div className="analytics-title"><div><p>PRODUCT METRICS</p><h1>BlinkRoom Analytics</h1></div><nav>{ranges.map(([value,label])=><button key={value} className={range===value?"active":""} onClick={()=>setRange(value)}>{label}</button>)}</nav></div>{loading&&<div className="analytics-state">Loading metrics…</div>}{error&&<div className="analytics-state analytics-error">{error} <button onClick={()=>void load()}>Retry</button></div>}{!loading&&data&&<>
    <div className="metric-grid">{cards.map(card=><article key={card.label}><span>{card.label}</span><strong>{card.value}</strong>{card.key?<Change value={data.comparison[card.key]??0} range={range}/>:<small className="metric-change neutral">Current snapshot</small>}</article>)}</div>
    <section className="analytics-section funnel-section"><SectionTitle label="01 / JOURNEY" title="Usage Funnel" detail="Aggregate events, not individual users"/><div className="funnel-grid">{data.funnel.map((step,index)=>{const prior=index?data.funnel[index-1].value:step.value,conversion=prior?step.value/prior*100:0;return <div key={step.label}><span>{step.label}</span><strong>{number(step.value,0)}</strong>{index>0&&<small>{number(conversion)}% from previous step</small>}</div>})}</div></section>
    <section className="analytics-section"><SectionTitle label="02 / TREND" title="Activity Over Time" detail={`${range==="24h"?"Hourly":"Daily"} buckets · UTC`}/><div className="metric-tabs">{metricOptions.map(([value,label])=><button key={value} className={metric===value?"active":""} onClick={()=>setMetric(value)}>{label}</button>)}</div>{data.timeline.length?<div className="line-chart" role="img" aria-label={`${metricOptions.find(x=>x[0]===metric)?.[1]} over time`}><svg viewBox="0 0 1000 230" preserveAspectRatio="none"><line x1="0" y1="220" x2="1000" y2="220"/><polyline points={chart}/>{data.timeline.map((point,index)=>{const max=Math.max(1,...data.timeline.map(p=>p[metric]));return <circle key={point.timestamp} cx={data.timeline.length===1?500:index/(data.timeline.length-1)*1000} cy={220-point[metric]/max*212} r="4"><title>{new Date(point.timestamp).toLocaleString("en",{timeZone:"UTC"})} UTC — {point[metric]}</title></circle>})}</svg></div>:<div className="analytics-state">No metrics in this range yet.</div>}</section>
    <section className="analytics-section"><SectionTitle label="03 / ROOMS" title="Room Analytics"/><StatGrid items={[["AVERAGE ROOM LIFETIME",duration(data.rooms.averageLifetimeMs)],["AVERAGE FILES / ROOM",number(data.rooms.averageFilesPerRoom)],["AVERAGE DOWNLOADS / ROOM",number(data.rooms.averageDownloadsPerRoom)],["EXPIRED ROOMS",data.rooms.expiredRooms],["MANUALLY DESTROYED",data.rooms.destroyedRooms],["CURRENTLY ACTIVE",data.rooms.activeRooms]]}/></section>
    <section className="analytics-section"><SectionTitle label="04 / FILES" title="File Analytics"/><StatGrid items={[["AVERAGE FILE SIZE",bytes(data.files.averageFileSize)],["LARGEST FILE",bytes(data.files.largestFile)],["TOTAL FILES",data.files.totalFiles],["DOWNLOADS / FILE",number(data.files.averageDownloadsPerFile)],["TOTAL UPLOADED",bytes(data.files.uploadBytes)],["TOTAL DOWNLOADED",bytes(data.files.downloadBytes)]]}/><div className="analytics-subsection"><span>FILE-TYPE DISTRIBUTION</span><Distribution values={data.files.distribution}/><small className="privacy-note">Categories are coarse and aggregate. Encrypted file metadata is never inspected; unclassified encrypted files appear as Other.</small></div></section>
    <section className="analytics-section split-section"><div><SectionTitle label="05 / DEVICE" title="Device Analytics"/><h3>DEVICE CLASS</h3><Distribution values={data.devices.device}/></div><div><h3>BROWSER</h3><Distribution values={data.devices.browser}/></div><p className="privacy-note">Based only on coarse, one-time session classification. BlinkRoom does not store IP addresses, user agents, fingerprints, or identities.</p></section>
    <section className="analytics-section recent-section"><SectionTitle label="06 / EVENTS" title="Recent Activity" detail="Anonymous · UTC"/>{data.recentActivity.length?<ol>{data.recentActivity.map((event,index)=><li key={`${event.timestamp}-${index}`}><time>{new Date(event.timestamp).toLocaleString("en",{timeZone:"UTC",hour12:false})}</time><span>{event.event}</span><i/></li>)}</ol>:<div className="analytics-state">No recent events in this period.</div>}</section>
    <section className="analytics-section"><SectionTitle label="07 / OPERATIONS" title="System / Transfer Health"/><StatGrid items={[["UPLOAD SUCCESS",`${number(data.health.uploadSuccessRate)}%`],["DOWNLOAD SUCCESS",`${number(data.health.downloadSuccessRate)}%`],["FAILED UPLOADS",data.health.failedUploads],["FAILED DOWNLOADS",data.health.failedDownloads],["AVERAGE UPLOAD DURATION",data.health.averageUploadDurationMs?duration(data.health.averageUploadDurationMs):"Collecting"],["TOTAL TRANSFER VOLUME",bytes(data.health.transferVolume)]]}/></section>
    <footer>Metrics are collected from {data.collectedFrom?new Date(data.collectedFrom).toLocaleString("en",{timeZone:"UTC",timeZoneName:"short"}):"the first event after deployment"}. All figures are aggregate and privacy-preserving. No IP logging, fingerprinting, or account-level analytics.</footer>
  </>}</section></main>
}
