"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
type Range = "24h" | "7d" | "30d" | "all";
type Data = { collectedFrom: string | null; summary: { visits: number; pageViews: number; roomsCreated: number; activeRooms: number; filesUploaded: number; filesDownloaded: number; uploadBytes: string; downloadBytes: string; averageFileSize: string; failedUploads: number; failedDownloads: number; conversionRate: number }; timeline: Array<{ timestamp: string; visits: number; pageViews: number; roomsCreated: number; filesUploaded: number; filesDownloaded: number }> };
const ranges: Array<[Range, string]> = [["24h", "24 Hours"], ["7d", "7 Days"], ["30d", "30 Days"], ["all", "All Time"]];
function bytes(value: string) { let amount = Number(value), unit = "B"; for (const next of ["KB", "MB", "GB", "TB", "PB"]) { if (amount < 1024) break; amount /= 1024; unit = next; } return `${amount >= 100 || unit === "B" ? amount.toFixed(0) : amount >= 10 ? amount.toFixed(1) : amount.toFixed(2)} ${unit}`; }
export function AnalyticsDashboard() {
  const [range, setRange] = useState<Range>("7d"), [data, setData] = useState<Data | null>(null), [loading, setLoading] = useState(true), [unauthorized, setUnauthorized] = useState(false), [error, setError] = useState("");
  const load = useCallback(async () => { await Promise.resolve(); setLoading(true); setError(""); try { const res = await fetch(`/api/admin/analytics?range=${range}`, { cache: "no-store" }); if (res.status === 401) { setUnauthorized(true); setData(null); return; } if (!res.ok) throw new Error(); setData(await res.json()); setUnauthorized(false); } catch { setError("Metrics could not be loaded."); } finally { setLoading(false); } }, [range]);
  // The state updates happen after the external fetch; this effect synchronizes
  // the selected range with the server-side metrics source.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  async function login(form: FormData) { setError(""); const res = await fetch("/api/admin/analytics/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: form.get("token") }) }); if (!res.ok) { setError("Invalid admin token."); return; } await load(); }
  if (unauthorized) return <main className="analytics-shell"><section className="analytics-login"><Link className="wordmark" href="/">BlinkRoom<i /></Link><p>PRIVATE METRICS</p><h1>BlinkRoom Analytics</h1><form action={login}><label htmlFor="token">Admin token</label><input id="token" name="token" type="password" autoComplete="current-password" required /><button className="button filled">Continue</button></form>{error && <span className="analytics-error">{error}</span>}</section></main>;
  const summary = data?.summary, cards = summary ? [["VISITS", summary.visits], ["ROOMS CREATED", summary.roomsCreated], ["ACTIVE ROOMS", summary.activeRooms], ["FILES UPLOADED", summary.filesUploaded], ["DOWNLOADS", summary.filesDownloaded], ["DATA UPLOADED", bytes(summary.uploadBytes)], ["DATA DOWNLOADED", bytes(summary.downloadBytes)], ["CONVERSION", `${summary.conversionRate.toFixed(1)}%`]] : [];
  const max = Math.max(1, ...(data?.timeline.map((point) => point.pageViews) ?? []));
  return <main className="analytics-shell"><header><Link className="wordmark" href="/">BlinkRoom<i /></Link><span>Privacy-first · UTC</span></header><section className="analytics-main"><div className="analytics-title"><div><p>PRODUCT METRICS</p><h1>BlinkRoom Analytics</h1></div><nav>{ranges.map(([value, label]) => <button key={value} className={range === value ? "active" : ""} onClick={() => setRange(value)}>{label}</button>)}</nav></div>{loading && <div className="analytics-state">Loading metrics…</div>}{error && <div className="analytics-state analytics-error">{error} <button onClick={() => void load()}>Retry</button></div>}{!loading && data && <><div className="metric-grid">{cards.map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><section className="chart-card"><div><span>PAGE VIEWS</span><small>{range === "24h" ? "Hourly" : "Daily"} buckets · UTC</small></div>{data.timeline.length ? <div className="chart" role="img" aria-label="Page views timeline">{data.timeline.map((point) => <div className="chart-column" key={point.timestamp} title={`${new Date(point.timestamp).toLocaleString("en", { timeZone: "UTC" })} UTC — ${point.pageViews} views`}><i style={{ height: `${Math.max(2, point.pageViews / max * 100)}%` }} /></div>)}</div> : <div className="analytics-state">No metrics in this range yet.</div>}</section><footer>Metrics are collected from {data.collectedFrom ? new Date(data.collectedFrom).toLocaleString("en", { timeZone: "UTC", timeZoneName: "short" }) : "the first event after deployment"}. Average upload: {bytes(summary!.averageFileSize)} · Failed uploads: {summary!.failedUploads} · Failed downloads: {summary!.failedDownloads}</footer></>}</section></main>;
}
