"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { io } from "socket.io-client";
import { ArrowUp, Check, ChevronUp, FileUp, Image as ImageIcon, LockKeyhole, MoreHorizontal, Paperclip, Plus, RotateCcw, Share2, Trash2, X } from "lucide-react";
import { brand } from "@/src/config/brand";
import type { DecryptedItem, ItemType, PublicItem, PublicRoom } from "@/src/lib/types";
import { InviteModal } from "./invite-modal";
import { ItemCard } from "./item-card";
import { roomDurations, type RoomTtlHours } from "@/src/lib/duration";
import { CRYPTO_VERSION } from "@/src/lib/crypto/constants";
import { decryptFileChunks, encryptedFileSize, encryptFileChunks, encryptFileMultipart } from "@/src/lib/crypto/file";
import { decryptJson, encryptJson, parseEnvelope } from "@/src/lib/crypto/payload";
import { importRoomKey, roomKeyFromFragment } from "@/src/lib/crypto/room-key";
import { WebRTCTransport } from "@/src/lib/transport/webrtc";
import { selectTransport } from "@/src/lib/transport/selection";
import type { Socket } from "socket.io-client";

type Upload = { id: string; file: File; progress: number; status: "encrypting" | "sending" | "uploading" | "failed" | "complete"; error?: string; direct?: boolean };
type Participant = { id: string; name: string };
type ItemSecret = { content?: string; senderName: string; fileName?: string; mimeType?: string; fileSize?: number };
type WebRTCConfig = { iceServers: RTCIceServer[]; connectionTimeoutMs: number; maxDirectPeers: number };
type StorageConfig = { directUpload: boolean; partSize: number; maxFileSize: number };
const getIdentity = () => { let id = localStorage.getItem("blinkroom_participant"); if (!id) { id = crypto.randomUUID(); localStorage.setItem("blinkroom_participant", id); } return { id, name: "Guest" }; };
const isSafeLink = (value: string) => { try { return ["http:", "https:"].includes(new URL(value).protocol); } catch { return false; } };
async function uploadMultipartStorage(input: { slug: string; itemId: string; senderId: string; type: "IMAGE" | "FILE"; encryptedMetadata: string; encrypted: Blob; directDelivered: boolean; signal: AbortSignal; onProgress: (value: number) => void }) {
  const created = await fetch(`/api/rooms/${input.slug}/uploads`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId: input.itemId, senderId: input.senderId, type: input.type, encryptionVersion: CRYPTO_VERSION, encryptedMetadata: input.encryptedMetadata, encryptedSize: input.encrypted.size, directDelivered: input.directDelivered }), signal: input.signal });
  if (!created.ok) throw new Error((await created.json().catch(() => null) as { error?: string } | null)?.error ?? "Temporary storage is unavailable right now.");
  const session = await created.json() as { sessionId: string; uploadToken: string; partSize: number; partCount: number }; const parts: Array<{ partNumber: number; etag: string }> = []; const authHeaders = { "Content-Type": "application/json", "x-upload-token": session.uploadToken };
  try { for (let index = 0; index < session.partCount; index++) { if (input.signal.aborted) throw new Error("Transfer cancelled"); const partNumber = index + 1; const signed = await fetch(`/api/rooms/${input.slug}/uploads/${session.sessionId}/parts`, { method: "POST", headers: authHeaders, body: JSON.stringify({ partNumber }), signal: input.signal }); if (!signed.ok) throw new Error("Temporary storage is unavailable right now."); const { url } = await signed.json() as { url: string }; const body = input.encrypted.slice(index * session.partSize, Math.min(input.encrypted.size, partNumber * session.partSize)); const etag = await new Promise<string>((resolve, reject) => { const xhr = new XMLHttpRequest(); const abort = () => xhr.abort(); input.signal.addEventListener("abort", abort, { once: true }); xhr.open("PUT", url); xhr.setRequestHeader("Content-Type", "application/octet-stream"); xhr.upload.onprogress = (event) => { if (event.lengthComputable) input.onProgress(Math.round((index * session.partSize + event.loaded) / input.encrypted.size * 100)); }; xhr.onload = () => { input.signal.removeEventListener("abort", abort); const value = xhr.getResponseHeader("etag"); if (xhr.status >= 200 && xhr.status < 300 && value) resolve(value); else reject(new Error("Temporary storage is unavailable right now.")); }; xhr.onerror = () => reject(new Error("Temporary storage is unavailable right now.")); xhr.onabort = () => reject(new Error("Transfer cancelled")); xhr.send(body); }); parts.push({ partNumber, etag }); }
    const completed = await fetch(`/api/rooms/${input.slug}/uploads/${session.sessionId}`, { method: "POST", headers: authHeaders, body: JSON.stringify({ parts }), signal: input.signal }); if (!completed.ok) throw new Error((await completed.json().catch(() => null) as { error?: string } | null)?.error ?? "Temporary storage is unavailable right now."); input.onProgress(100);
  } catch (error) { await fetch(`/api/rooms/${input.slug}/uploads/${session.sessionId}`, { method: "DELETE", headers: { "x-upload-token": session.uploadToken } }).catch(() => undefined); throw error; }
}
async function uploadStreamingStorage(input: { slug: string; itemId: string; senderId: string; type: "IMAGE" | "FILE"; encryptedMetadata: string; key: CryptoKey; file: File; partSize: number; signal: AbortSignal; onEncrypt: (value: number) => void; onUpload: (value: number) => void }) { const size = encryptedFileSize(input.file.size); const created = await fetch(`/api/rooms/${input.slug}/uploads`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId: input.itemId, senderId: input.senderId, type: input.type, encryptionVersion: CRYPTO_VERSION, encryptedMetadata: input.encryptedMetadata, encryptedSize: size, directDelivered: false }), signal: input.signal }); if (!created.ok) throw new Error((await created.json().catch(() => null) as { error?: string } | null)?.error ?? "Temporary storage is unavailable right now."); const session = await created.json() as { sessionId: string; uploadToken: string; partSize: number; partCount: number }; const authHeaders = { "Content-Type": "application/json", "x-upload-token": session.uploadToken }, parts: Array<{ partNumber: number; etag: string }> = []; let uploaded = 0, partNumber = 0;
  try { for await (const body of encryptFileMultipart(input.key, input.file, input.slug, input.itemId, session.partSize, input.onEncrypt)) { partNumber++; const signed = await fetch(`/api/rooms/${input.slug}/uploads/${session.sessionId}/parts`, { method: "POST", headers: authHeaders, body: JSON.stringify({ partNumber }), signal: input.signal }); if (!signed.ok) throw new Error("Temporary storage is unavailable right now."); const { url } = await signed.json() as { url: string }; const etag = await new Promise<string>((resolve, reject) => { const xhr = new XMLHttpRequest(), abort = () => xhr.abort(); input.signal.addEventListener("abort", abort, { once: true }); xhr.open("PUT", url); xhr.setRequestHeader("Content-Type", "application/octet-stream"); xhr.upload.onprogress = (event) => event.lengthComputable && input.onUpload(Math.round((uploaded + event.loaded) / size * 100)); xhr.onload = () => { input.signal.removeEventListener("abort", abort); const value = xhr.getResponseHeader("etag"); if (xhr.status >= 200 && xhr.status < 300 && value) resolve(value); else reject(new Error("Temporary storage is unavailable right now.")); }; xhr.onerror = () => reject(new Error("Temporary storage is unavailable right now.")); xhr.onabort = () => reject(new Error("Transfer cancelled")); xhr.send(body); }); parts.push({ partNumber, etag }); uploaded += body.size; }
    if (partNumber !== session.partCount) throw new Error("Temporary storage is unavailable right now."); const completed = await fetch(`/api/rooms/${input.slug}/uploads/${session.sessionId}`, { method: "POST", headers: authHeaders, body: JSON.stringify({ parts }), signal: input.signal }); if (!completed.ok) throw new Error((await completed.json().catch(() => null) as { error?: string } | null)?.error ?? "Temporary storage is unavailable right now."); input.onUpload(100);
  } catch (error) { await fetch(`/api/rooms/${input.slug}/uploads/${session.sessionId}`, { method: "DELETE", headers: { "x-upload-token": session.uploadToken } }).catch(() => undefined); throw error; }
}

export function RoomClient({ slug, isOwner }: { slug: string; isOwner: boolean }) {
  const [room, setRoom] = useState<PublicRoom | null>(null); const [items, setItems] = useState<DecryptedItem[]>([]); const [identity, setIdentity] = useState({ id: "", name: "Guest" });
  const [keyError, setKeyError] = useState<"missing" | "unlock" | "">(""); const [cryptoKey, setCryptoKey] = useState<CryptoKey | null>(null); const [error, setError] = useState(""); const [status, setStatus] = useState<"connecting"|"connected"|"offline">("connecting"); const [participants, setParticipants] = useState<Participant[]>([]);
  const [events, setEvents] = useState<{ id: string; text: string }[]>([]); const [invite, setInvite] = useState(false); const [destroy, setDestroy] = useState(false); const [sheet, setSheet] = useState(false); const [menu, setMenu] = useState(false); const [lifetime, setLifetime] = useState(false); const [feedback, setFeedback] = useState("");
  const [draft, setDraft] = useState(""); const [uploads, setUploads] = useState<Upload[]>([]); const [dragging, setDragging] = useState(false); const [preview, setPreview] = useState<DecryptedItem | null>(null); const [now, setNow] = useState(0);
  const fileRef = useRef<HTMLInputElement>(null); const photoRef = useRef<HTMLInputElement>(null); const bottomRef = useRef<HTMLDivElement>(null); const keyRef = useRef<CryptoKey | null>(null); const itemsRef = useRef<DecryptedItem[]>([]); const pendingXhrs = useRef(new Set<XMLHttpRequest>()); const transferControllers = useRef(new Map<string, AbortController>()); const directBlobs = useRef(new Map<string, Blob>()); const transportRef = useRef<WebRTCTransport | null>(null); const transportConfig = useRef<WebRTCConfig | null>(null); const storageConfig = useRef<StorageConfig | null>(null); const participantsRef = useRef<Participant[]>([]);

  const replaceItems = useCallback((next: DecryptedItem[]) => { for (const item of itemsRef.current) if (item.objectUrl && !next.some((candidate) => candidate.objectUrl === item.objectUrl)) URL.revokeObjectURL(item.objectUrl); itemsRef.current = next; setItems(next); }, []);
  const clearSecrets = useCallback(() => { for (const item of itemsRef.current) if (item.objectUrl) URL.revokeObjectURL(item.objectUrl); itemsRef.current = []; setItems([]); keyRef.current = null; setCryptoKey(null); for (const xhr of pendingXhrs.current) xhr.abort(); pendingXhrs.current.clear(); for (const controller of transferControllers.current.values()) controller.abort(); transferControllers.current.clear(); transportRef.current?.close(); transportRef.current = null; directBlobs.current.clear(); setUploads([]); setPreview(null); }, []);
  const decryptItem = useCallback(async (key: CryptoKey, item: PublicItem): Promise<DecryptedItem> => {
    if (item.encryptionVersion !== CRYPTO_VERSION) throw new Error("Unsupported crypto version");
    if (item.type === "TEXT" || item.type === "LINK") { if (!item.encryptedPayload) throw new Error("Missing encrypted payload"); const secret = await decryptJson<ItemSecret>(key, parseEnvelope(item.encryptedPayload), `${slug}:${item.id}:content:v1`); if (!secret.content || (item.type === "LINK" && !isSafeLink(secret.content))) throw new Error("Invalid encrypted content"); return { ...item, senderName: secret.senderName, textContent: secret.content, fileName: null, fileSize: null, mimeType: null }; }
    if (!item.encryptedMetadata) throw new Error("Missing encrypted metadata"); const secret = await decryptJson<ItemSecret>(key, parseEnvelope(item.encryptedMetadata), `${slug}:${item.id}:metadata:v1`); if (!secret.fileName || !secret.mimeType || typeof secret.fileSize !== "number") throw new Error("Invalid encrypted metadata");
    const localEncrypted = directBlobs.current.get(item.id); const stored = item.availability !== "DIRECT"; const decrypted: DecryptedItem = { ...item, senderName: secret.senderName, textContent: null, fileName: secret.fileName, fileSize: secret.fileSize, mimeType: secret.mimeType, locallyAvailable: Boolean(localEncrypted) || stored };
    if (item.type === "IMAGE" && (localEncrypted || stored)) { let encrypted: Blob; if (localEncrypted) encrypted = localEncrypted; else encrypted = await fetch(`/api/files/${encodeURIComponent(slug)}/${encodeURIComponent(item.id)}`).then((response) => { if (!response.ok) throw new Error("Encrypted file unavailable"); return response.blob(); }); const blob = await decryptFileChunks(key, encrypted, slug, item.id, secret.mimeType); decrypted.objectUrl = URL.createObjectURL(blob); }
    return decrypted;
  }, [slug]);
  const sync = useCallback(async (key = keyRef.current) => { if (!key) return; const res = await fetch(`/api/rooms/${slug}`); if (!res.ok) { setError(res.status === 404 ? "not-found" : "unavailable"); return; } const data = await res.json() as PublicRoom; if (data.status !== "ACTIVE") { clearSecrets(); setError(data.status.toLowerCase()); return; } try { if (!data.encryptedVerifier || data.encryptionVersion !== CRYPTO_VERSION) throw new Error("Missing verifier"); const verifier = await decryptJson<{ check: string }>(key, parseEnvelope(data.encryptedVerifier), `${slug}:verifier:v1`); if (verifier.check !== "blinkroom-room-key") throw new Error("Invalid verifier"); const decrypted = await Promise.all(data.items.map((item) => decryptItem(key, item))); setRoom(data); replaceItems(decrypted); } catch { setKeyError("unlock"); clearSecrets(); } }, [clearSecrets, decryptItem, replaceItems, slug]);

  useEffect(() => { const serialized = roomKeyFromFragment(window.location.hash); if (!serialized) { queueMicrotask(() => setKeyError("missing")); return; } const me = getIdentity(); queueMicrotask(() => setIdentity(me)); importRoomKey(serialized).then((key) => { keyRef.current = key; setCryptoKey(key); }).catch(() => setKeyError("unlock")); return clearSecrets; }, [clearSecrets]);
  useEffect(() => { void fetch("/api/storage-config").then((response) => response.json()).then((config: StorageConfig) => { storageConfig.current = config; }).catch(() => undefined); }, []);
  useEffect(() => { if (!cryptoKey) return; queueMicrotask(() => sync(cryptoKey)); const me = getIdentity(); const socket: Socket = io({ path: "/api/socket" });
    void fetch("/api/webrtc-config").then((response) => response.json()).then((config: WebRTCConfig) => { if (!socket.connected) return; transportConfig.current = config; transportRef.current?.close(); transportRef.current = new WebRTCTransport(socket, me.id, config, { onReceive: async (file) => { directBlobs.current.set(file.itemId, file.encrypted); setFeedback("Direct transfer ready."); setTimeout(() => setFeedback(""), 1400); }, onProgress: ({ itemId, direction, progress }) => { if (direction === "sending") setUploads((current) => current.map((upload) => upload.id === itemId ? { ...upload, status: "sending", direct: true, progress } : upload)); }, onError: () => undefined }); transportRef.current.setPeers(participantsRef.current.map((participant) => participant.id)); }).catch(() => undefined);
    socket.on("connect", () => { if (!transportRef.current) void fetch("/api/webrtc-config").then((response) => response.json()).then((config: WebRTCConfig) => { transportConfig.current = config; transportRef.current = new WebRTCTransport(socket, me.id, config, { onReceive: async (file) => { directBlobs.current.set(file.itemId, file.encrypted); setFeedback("Direct transfer ready."); setTimeout(() => setFeedback(""), 1400); }, onProgress: ({ itemId, direction, progress }) => { if (direction === "sending") setUploads((current) => current.map((upload) => upload.id === itemId ? { ...upload, status: "sending", direct: true, progress } : upload)); } }); transportRef.current.setPeers(participantsRef.current.map((participant) => participant.id)); }).catch(() => undefined); });
    socket.on("connect", () => { setStatus("connected"); setFeedback("Connected"); setTimeout(() => setFeedback(""), 1200); socket.emit("room:join", { slug, participantId: me.id, name: isOwner ? "Room owner" : "Guest" }); sync(cryptoKey); }); socket.on("disconnect", () => setStatus(navigator.onLine ? "connecting" : "offline")); socket.on("connect_error", () => setStatus("connecting")); socket.on("presence:update", (next: Participant[]) => { participantsRef.current = next; setParticipants(next); transportRef.current?.setPeers(next.map((participant) => participant.id)); }); socket.on("presence:event", ({ kind, name }) => setEvents((current) => [...current.slice(-4), { id: crypto.randomUUID(), text: `${name || "Someone"} ${kind}` }]));
    socket.on("item:create", async (item: PublicItem) => { try { const decrypted = await decryptItem(cryptoKey, item); const position = itemsRef.current.findIndex((existing) => existing.id === item.id); replaceItems(position < 0 ? [...itemsRef.current, decrypted] : itemsRef.current.map((existing) => existing.id === item.id ? decrypted : existing)); setRoom((current) => current ? { ...current, items: current.items.some((existing) => existing.id === item.id) ? current.items.map((existing) => existing.id === item.id ? item : existing) : [...current.items, item] } : current); } catch { setKeyError("unlock"); clearSecrets(); } });
    socket.on("item:delete", ({ id }) => { replaceItems(itemsRef.current.filter((item) => item.id !== id)); setRoom((current) => current ? { ...current, items: current.items.filter((item) => item.id !== id) } : current); }); socket.on("room:destroy", () => { clearSecrets(); setError("destroyed"); }); socket.on("room:expired", () => { clearSecrets(); setError("expired"); }); socket.on("room:expiration-updated", ({ expiresAt }: { expiresAt: string }) => setRoom((current) => current ? { ...current, expiresAt } : current));
    const online = () => { setStatus(socket.connected ? "connected" : "connecting"); socket.connect(); }; const offline = () => setStatus("offline"); window.addEventListener("online", online); window.addEventListener("offline", offline); return () => { transportRef.current?.close(); transportRef.current = null; socket.disconnect(); window.removeEventListener("online", online); window.removeEventListener("offline", offline); };
  }, [clearSecrets, cryptoKey, decryptItem, isOwner, replaceItems, slug, sync]);
  useEffect(() => { queueMicrotask(() => setNow(Date.now())); const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []); useEffect(() => { if (!cryptoKey) return; const timer = setInterval(() => sync(cryptoKey), 30_000); return () => clearInterval(timer); }, [cryptoKey, sync]); useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: "smooth" }); }, [items.length, uploads.length]);

  const senderName = participants.find((participant) => participant.id === identity.id)?.name ?? (isOwner ? "Room owner" : "Guest");
  const shareText = useCallback(async (value = draft) => { const content = value.trim(), key = keyRef.current; if (!content || !identity.id || !key) return; const type: ItemType = isSafeLink(content) ? "LINK" : "TEXT"; const itemId = crypto.randomUUID(); const encryptedPayload = JSON.stringify(await encryptJson(key, { content, senderName }, `${slug}:${itemId}:content:v1`)); const res = await fetch(`/api/rooms/${slug}/items/text`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId, senderId: identity.id, type, encryptionVersion: CRYPTO_VERSION, encryptedPayload }) }); if (res.ok) setDraft(""); }, [draft, identity.id, senderName, slug]);
  const uploadOne = useCallback(async (file: File, existingId?: string) => {
    const key = keyRef.current; if (!key || !identity.id) return; const id = existingId ?? crypto.randomUUID(); if (transferControllers.current.has(id)) return; const controller = new AbortController(); transferControllers.current.set(id, controller);
    setUploads((current) => existingId ? current.map((item) => item.id === id ? { ...item, progress: 0, status: "encrypting", error: undefined } : item) : [...current, { id, file, progress: 0, status: "encrypting" }]);
    try { if (storageConfig.current && file.size > storageConfig.current.maxFileSize) throw new Error("This file is too large.");
      const type: "IMAGE" | "FILE" = ["image/jpeg", "image/png", "image/webp", "image/gif"].includes(file.type) ? "IMAGE" : "FILE";
      const encryptedMetadata = JSON.stringify(await encryptJson(key, { fileName: file.name, mimeType: file.type || "application/octet-stream", fileSize: file.size, senderName }, `${slug}:${id}:metadata:v1`));
      const peers = participantsRef.current.filter((participant) => participant.id !== identity.id).map((participant) => participant.id); const config = transportConfig.current; const direct = config && transportRef.current && selectTransport(peers.length, config.maxDirectPeers, typeof RTCPeerConnection !== "undefined") === "DIRECT";
      if (!direct && storageConfig.current?.directUpload) { await uploadStreamingStorage({ slug, itemId: id, senderId: identity.id, type, encryptedMetadata, key, file, partSize: storageConfig.current.partSize, signal: controller.signal, onEncrypt: (progress) => setUploads((current) => current.map((item) => item.id === id ? { ...item, status: "encrypting", progress: Math.round(progress * .35) } : item)), onUpload: (progress) => setUploads((current) => current.map((item) => item.id === id ? { ...item, status: "uploading", progress: 35 + Math.round(progress * .65) } : item)) }); setUploads((current) => current.map((item) => item.id === id ? { ...item, progress: 100, status: "complete" } : item)); setTimeout(() => setUploads((current) => current.filter((item) => item.id !== id)), 900); return; }
      const encryptedFile = await encryptFileChunks(key, file, slug, id, (progress) => setUploads((current) => current.map((item) => item.id === id ? { ...item, progress: Math.round(progress * .35), status: "encrypting" } : item))); if (controller.signal.aborted) throw new Error("Cancelled"); directBlobs.current.set(id, encryptedFile);
      let delivered = 0;
      if (direct) { setUploads((current) => current.map((item) => item.id === id ? { ...item, status: "sending", direct: true, progress: 35 } : item)); const result = await transportRef.current!.sendFile({ itemId: id, type, encryptedMetadata, encrypted: encryptedFile }, peers, controller.signal); delivered = result.delivered.length; if (delivered === peers.length) { const response = await fetch(`/api/rooms/${slug}/items/direct`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId: id, senderId: identity.id, type, encryptionVersion: CRYPTO_VERSION, encryptedMetadata, encryptedSize: encryptedFile.size }), signal: controller.signal }); if (response.ok) { setUploads((current) => current.map((item) => item.id === id ? { ...item, progress: 100, status: "complete" } : item)); setTimeout(() => setUploads((current) => current.filter((item) => item.id !== id)), 900); transferControllers.current.delete(id); return; } } }
      if (controller.signal.aborted) throw new Error("Cancelled"); if (storageConfig.current?.directUpload) { setUploads((current) => current.map((item) => item.id === id ? { ...item, status: "uploading", direct: false, progress: 35 } : item)); await uploadMultipartStorage({ slug, itemId: id, senderId: identity.id, type, encryptedMetadata, encrypted: encryptedFile, directDelivered: delivered > 0, signal: controller.signal, onProgress: (progress) => setUploads((current) => current.map((item) => item.id === id ? { ...item, status: "uploading", progress: 35 + Math.round(progress * .65) } : item)) }); setUploads((current) => current.map((item) => item.id === id ? { ...item, progress: 100, status: "complete" } : item)); setTimeout(() => setUploads((current) => current.filter((item) => item.id !== id)), 900); return; } const form = new FormData(); form.append("itemId", id); form.append("senderId", identity.id); form.append("type", type); form.append("encryptionVersion", String(CRYPTO_VERSION)); form.append("encryptedMetadata", encryptedMetadata); form.append("directDelivered", delivered > 0 ? "true" : "false"); form.append("file", encryptedFile, "encrypted.bin");
      await new Promise<void>((resolve) => { const xhr = new XMLHttpRequest(); pendingXhrs.current.add(xhr); const abort = () => xhr.abort(); controller.signal.addEventListener("abort", abort, { once: true }); xhr.open("POST", `/api/rooms/${slug}/items/upload`); xhr.upload.onprogress = (event) => event.lengthComputable && setUploads((current) => current.map((item) => item.id === id ? { ...item, progress: 35 + Math.round(event.loaded / event.total * 65), status: "uploading", direct: false } : item)); xhr.onload = () => { pendingXhrs.current.delete(xhr); controller.signal.removeEventListener("abort", abort); if (xhr.status < 300) { setUploads((current) => current.map((item) => item.id === id ? { ...item, progress: 100, status: "complete" } : item)); setTimeout(() => setUploads((current) => current.filter((item) => item.id !== id)), 900); } else setUploads((current) => current.map((item) => item.id === id ? { ...item, status: "failed", error: "Transfer failed" } : item)); resolve(); }; xhr.onerror = () => { pendingXhrs.current.delete(xhr); setUploads((current) => current.map((item) => item.id === id ? { ...item, status: "failed", error: "Network error" } : item)); resolve(); }; xhr.onabort = () => { pendingXhrs.current.delete(xhr); setUploads((current) => current.map((item) => item.id === id ? { ...item, status: "failed", error: "Transfer cancelled" } : item)); resolve(); }; xhr.send(form); });
    } catch (cause) { const message = cause instanceof Error ? cause.message : ""; const cancelled = controller.signal.aborted || message === "Cancelled" || message === "Transfer cancelled"; const friendly = ["This file is too large.", "This room has reached its temporary storage limit.", "This room has reached its item limit.", "Too many uploads are already in progress.", "Temporary storage is unavailable right now."].includes(message) ? message : "Couldn’t send this file. Try again."; setUploads((current) => current.map((item) => item.id === id ? { ...item, status: "failed", error: cancelled ? "Transfer cancelled" : friendly } : item)); } finally { transferControllers.current.delete(id); }
  }, [identity.id, senderName, slug]);
  const uploadFiles = useCallback(async (files: FileList | File[]) => { await Promise.all(Array.from(files).map((file) => uploadOne(file))); }, [uploadOne]);
  useEffect(() => { const paste = (event: ClipboardEvent) => { const image = [...(event.clipboardData?.items ?? [])].find((item) => item.kind === "file" && item.type.startsWith("image/")); if (image) { const blob = image.getAsFile(); if (blob) { event.preventDefault(); const extension = blob.type.split("/")[1]?.replace("jpeg", "jpg") || "png"; setFeedback("Image pasted"); setTimeout(() => setFeedback(""), 1500); uploadFiles([new File([blob], `pasted-image-${Date.now()}.${extension}`, { type: blob.type })]); } } else { const text = event.clipboardData?.getData("text"); if (text && document.activeElement?.tagName !== "INPUT" && document.activeElement?.tagName !== "TEXTAREA") { event.preventDefault(); setDraft(text); setFeedback("Text pasted"); setTimeout(() => setFeedback(""), 1200); } } }; window.addEventListener("paste", paste); return () => window.removeEventListener("paste", paste); }, [uploadFiles]);

  if (keyError) return <KeyState kind={keyError} />; if (error) return <StateScreen kind={error} />; if (!room) return <div className="room-loading"><span className="wordmark">{brand.name}<i /></span><div className="loader" /></div>;
  const left = Math.max(0, new Date(room.expiresAt).getTime() - now); const timerLabel = formatRemaining(left); const roomUrl = typeof window !== "undefined" ? window.location.href : "";
  async function deleteItem(id: string) { await fetch(`/api/rooms/${slug}/items/${id}`, { method: "DELETE", headers: { "x-participant-id": identity.id } }); }
  async function downloadItem(item: DecryptedItem) { const key = keyRef.current; if (!key || !item.fileName || !item.mimeType) return; try { const local = directBlobs.current.get(item.id); let encrypted: Blob; if (local) encrypted = local; else encrypted = await fetch(`/api/files/${encodeURIComponent(slug)}/${encodeURIComponent(item.id)}`).then((response) => { if (!response.ok) throw new Error("Unavailable"); return response.blob(); }); const blob = await decryptFileChunks(key, encrypted, slug, item.id, item.mimeType); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = item.fileName; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); } catch { setFeedback(item.availability === "DIRECT" ? "No longer available." : "Unable to decrypt file."); setTimeout(() => setFeedback(""), 1600); } }
  async function destroyRoom() { const res = await fetch(`/api/rooms/${slug}`, { method: "DELETE" }); if (res.ok) { clearSecrets(); setError("destroyed"); } }
  async function updateLifetime(ttlHours: RoomTtlHours) { const res = await fetch(`/api/rooms/${slug}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ttlHours }) }); if (!res.ok) { if (res.status === 409 || res.status === 410) { clearSecrets(); setError("expired"); } return; } const data = await res.json() as { expiresAt: string }; setRoom((current) => current ? { ...current, expiresAt: data.expiresAt } : current); setLifetime(false); setFeedback("Lifetime updated."); setTimeout(() => setFeedback(""), 1600); }
  return <main className="room-shell" onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); setDragging(false); uploadFiles(event.dataTransfer.files); }}>
    {dragging && <div className="drop-overlay" onDragLeave={() => setDragging(false)}><strong>DROP IT.</strong><span>Everyone in the room will see it.</span></div>}{feedback && <div className="feedback-toast"><Check/>{feedback}</div>}
    <header className="room-header"><div className="header-main"><Link className="wordmark" href="/">{brand.name}<i /></Link><div className="room-code"><span>ROOM</span><strong>{slug}</strong></div><button className="presence-count" onClick={() => setMenu(false)}><i/>{participants.length} online</button><div className="e2ee-label" title="Shared content is encrypted in your browser. BlinkRoom does not receive the room encryption key."><LockKeyhole/> End-to-end encrypted</div><div className="lifetime-wrap">{isOwner ? <button className={`room-timer owner ${left < 3600000 ? "ending" : ""} ${left < 300000 ? "urgent" : ""}`} onClick={() => setLifetime(!lifetime)}>{timerLabel}</button> : <div className={`room-timer ${left < 3600000 ? "ending" : ""} ${left < 300000 ? "urgent" : ""}`}>{timerLabel}</div>}{lifetime && isOwner && <div className="lifetime-popover"><strong>Room lifetime</strong><span>Expires in {formatExpirationSummary(left)}</span><div>{roomDurations.map((duration) => <button key={duration.hours} onClick={() => updateLifetime(duration.hours)}>{duration.label}</button>)}</div></div>}</div><div className="header-actions"><button className="button" onClick={() => setInvite(true)}><Share2/> Invite</button><div className="more-wrap"><button className="more-button" onClick={() => setMenu(!menu)} aria-label="Room menu"><MoreHorizontal/></button>{menu && <div className="room-menu">{isOwner ? <button onClick={() => { setDestroy(true); setMenu(false); }}><Trash2/> Destroy room</button> : <span>No room actions</span>}</div>}</div></div><button className="mobile-menu" onClick={() => setInvite(true)}><Share2/></button>{isOwner && <button className="mobile-more" onClick={() => setMenu(!menu)}><MoreHorizontal/></button>}{menu && isOwner && <div className="mobile-room-menu"><button onClick={() => { setDestroy(true); setMenu(false); }}><Trash2/> Destroy room</button></div>}</div>{status !== "connected" && <div className="connection-strip">{status === "offline" ? "You’re offline" : "Reconnecting…"}</div>}</header>
    <section className="timeline"><div className="timeline-intro"><span>SHARED IN THIS ROOM</span><p>Everything here disappears when the room ends.</p></div>{!items.length && !uploads.length && <div className="empty"><h1>Drop anything.</h1><p>Files, photos, text or links.</p><small>Everyone in this room sees it instantly.</small><button className="button" onClick={() => fileRef.current?.click()}><Paperclip/> Choose a file</button></div>}<div className="items">{items.map((item) => <ItemCard key={item.id} item={item} you={item.senderId === identity.id} onDelete={() => deleteItem(item.id)} onPreview={() => setPreview(item)} onDownload={() => downloadItem(item)} />)}{uploads.map((upload) => <div className={`upload-card ${upload.status}`} key={upload.id}><FileUp/><div><strong>{upload.file.name}</strong><small>{formatSize(upload.file.size)}</small><span>{upload.status === "failed" ? (upload.error ?? "Transfer failed") : upload.status === "complete" ? "Ready" : upload.status === "encrypting" ? `Encrypting · ${upload.progress}%` : upload.status === "sending" ? `Sending · ${upload.progress}%` : `Uploading securely · ${upload.progress}%`}</span>{upload.status !== "failed" && <i><b style={{ width: `${upload.progress}%` }} /></i>}</div>{upload.status === "complete" ? <Check/> : upload.status === "failed" ? <div className="upload-actions"><button onClick={() => uploadOne(upload.file, upload.id)}><RotateCcw/> Retry</button><button onClick={() => setUploads((all) => all.filter((item) => item.id !== upload.id))}>Remove</button></div> : <button className="transfer-cancel" aria-label="Cancel transfer" onClick={() => transferControllers.current.get(upload.id)?.abort()}><X/></button>}</div>)}{events.map((event) => <div className="system-event" key={event.id}><span>{event.text}</span></div>)}<div ref={bottomRef}/></div></section>
    <div className="composer"><div className="composer-inner"><button className="add-button" onClick={() => setSheet(true)}><Plus/></button><textarea value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); shareText(); } }} rows={1} placeholder="Paste or type anything…"/><button className="send-button" onClick={() => shareText()} disabled={!draft.trim()}><ArrowUp/></button></div><span>Press Enter to share · Shift + Enter for a new line</span></div>
    <input hidden multiple ref={fileRef} type="file" onChange={(event) => event.target.files && uploadFiles(event.target.files)} /><input hidden multiple ref={photoRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={(event) => event.target.files && uploadFiles(event.target.files)} />
    {invite && <InviteModal url={roomUrl} onClose={() => setInvite(false)} />}{destroy && <ConfirmDestroy onClose={() => setDestroy(false)} onConfirm={destroyRoom} />}{sheet && <div className="sheet-backdrop" onClick={() => setSheet(false)}><div className="bottom-sheet" onClick={(event) => event.stopPropagation()}><div className="sheet-handle"/><h3>Add to room</h3><div className="sheet-options"><button onClick={() => {fileRef.current?.click();setSheet(false)}}><FileUp/><span>Upload file</span></button><button onClick={() => {photoRef.current?.click();setSheet(false)}}><ImageIcon/><span>Choose photo</span></button></div><button className="sheet-close" onClick={() => setSheet(false)}>Cancel</button></div></div>}{preview?.objectUrl && <div className="lightbox" onClick={() => setPreview(null)}><button><X/></button>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={preview.objectUrl} alt={preview.fileName ?? "Preview"}/><button className="button filled" onClick={() => downloadItem(preview)}><FileUp/> Download</button></div>}
  </main>;
}
function ConfirmDestroy({ onClose, onConfirm }: { onClose: () => void; onConfirm: () => void }) { return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal confirm" onMouseDown={(event)=>event.stopPropagation()}><div className="warning"><Trash2/></div><h2>Destroy this room?</h2><p>Everything shared here will disappear immediately.</p><strong>This cannot be undone.</strong><div className="modal-actions"><button className="button" onClick={onClose}>Cancel</button><button className="button destroy" onClick={onConfirm}>Destroy room</button></div></section></div>; }
function KeyState({ kind }: { kind: "missing" | "unlock" }) { const copy = kind === "missing" ? ["Missing room key.", "This link is incomplete. Ask the room owner for the original invite link."] : ["Unable to unlock this room.", "The invite key is invalid or the encrypted content could not be verified."]; return <main className="state-screen"><Link className="wordmark" href="/">{brand.name}<i/></Link><div><span className="state-icon"><LockKeyhole/></span><h1>{copy[0]}</h1><p>{copy[1]}</p><Link href="/" className="button filled">Create a room <ChevronUp/></Link></div></main>; }
function StateScreen({ kind }: { kind: string }) { const copy = kind === "expired" ? ["Time’s up.", "This room has expired and its contents are no longer available.", "Create another room"] : kind === "destroyed" ? ["This room is gone.", "Everything shared here is no longer available.", "Create another room"] : kind === "not-found" ? ["Nothing here.", "This room doesn’t exist or is no longer available.", "Create a room"] : ["This room is unavailable.", "Please try again in a moment.", "Create a room"]; return <main className="state-screen"><Link className="wordmark" href="/">{brand.name}<i/></Link><div><span className="state-icon"><X/></span><h1>{copy[0]}</h1><p>{copy[1]}</p><Link href="/" className="button filled">{copy[2]} <ChevronUp/></Link></div></main>; }
function formatSize(n: number) { return n >= 1048576 ? `${(n / 1048576).toFixed(1)} MB` : `${Math.max(1, Math.ceil(n / 1024))} KB`; }
function formatRemaining(ms: number) { if (ms >= 86_400_000) return `${Math.floor(ms / 86_400_000)}d ${Math.floor(ms % 86_400_000 / 3_600_000)}h left`; return `${String(Math.floor(ms / 3_600_000)).padStart(2, "0")}:${String(Math.floor(ms % 3_600_000 / 60_000)).padStart(2, "0")}:${String(Math.floor(ms % 60_000 / 1000)).padStart(2, "0")} left`; }
function formatExpirationSummary(ms: number) { if (ms >= 86_400_000) return `${Math.floor(ms / 86_400_000)}d ${Math.floor(ms % 86_400_000 / 3_600_000)}h`; return `${Math.floor(ms / 3_600_000)}h ${Math.floor(ms % 3_600_000 / 60_000)}m`; }
