"use client";

import { useEffect, useState } from "react";
import { ArrowRight, FileText, Maximize2, Pause, Play, X } from "lucide-react";

const SCENE_MS = 2000;
const SCENE_COUNT = 7;

function ProcessScene({ scene }: { scene: number }) {
  switch (scene) {
    case 0: return <div className="security-process-scene room-created"><span>ROOM CREATED</span><strong>K7F2–XM</strong><p>Temporary by design</p><code>23:59:59 remaining</code><small>Illustrative room · 24-hour example</small></div>;
    case 1: return <div className="security-process-scene file-process"><div className="process-file"><FileText /><span>presentation.pdf</span></div><ol><li>ENCRYPTING IN BROWSER</li><li>AES-GCM</li><li>TEMPORARY STORAGE</li><li>READY TO SHARE</li></ol></div>;
    case 2: return <div className="security-process-scene storage-flow"><span>WHAT HAPPENS TO YOUR FILE?</span><div><b>YOUR DEVICE</b><i>↓</i><b>ENCRYPTED TRANSFER</b><i>↓</i><b>TEMPORARY STORAGE</b><i>↓</i><b>RECIPIENT</b></div><p>Not designed as permanent cloud storage.</p></div>;
    case 3: return <div className="security-process-scene direct-flow"><span>DIRECT TRANSFERS ONLY</span><em>OPTIONAL MODE</em><div><b>YOUR DEVICE</b><i>→</i><b>RECIPIENT</b></div><p>WebRTC DataChannel transfer. Temporary file storage is bypassed.</p></div>;
    case 4: return <div className="security-process-scene control-flow"><span>YOU DECIDE WHEN IT ENDS.</span><ul><li>AUTOMATIC EXPIRY <b>ALWAYS</b></li><li>DESTROY WHEN EVERYONE LEAVES <b>OPTIONAL</b></li><li>DESTROY ROOM NOW <b>OWNER</b></li></ul></div>;
    case 5: return <div className="security-process-scene destruction-flow"><span>ROOM EXPIRED</span><strong>ACCESS ENDED</strong><div>REMOVING ENCRYPTED FILES…</div><p>Cleanup runs asynchronously and retries if needed.</p></div>;
    default: return <div className="security-process-scene final-flow"><strong>Built to share.<br />Designed to disappear.</strong><p>See exactly how BlinkRoom handles your files.</p></div>;
  }
}

function ArchitectureView({ onClose }: { onClose: () => void }) {
  return <div className="security-architecture-backdrop" onMouseDown={onClose}>
    <section className="security-architecture" role="dialog" aria-modal="true" aria-labelledby="security-architecture-title" onMouseDown={(event) => event.stopPropagation()}>
      <header><div><span>BLINKROOM SECURITY</span><h2 id="security-architecture-title">Don’t trust a privacy slogan.<br />See how it works.</h2></div><button onClick={onClose} aria-label="Close security architecture"><X /></button></header>
      <div className="security-architecture-grid">
        <article><span>01 · FILE LIFECYCLE</span><h3>Encrypted before it leaves your browser.</h3><p>Your browser encrypts file bytes and identifying metadata, then sends ciphertext through temporary storage or directly to a connected recipient. Recipients decrypt in their browsers.</p><div className="architecture-line"><b>DEVICE</b><i>→</i><b>ENCRYPTED TRANSFER</b><i>→</i><b>RECIPIENT</b></div></article>
        <article><span>02 · TEMPORARY STORAGE</span><h3>Storage is a transport step, not a permanent library.</h3><p>Standard transfers can temporarily store encrypted objects. Deployments support local object storage or Cloudflare R2; R2 receives opaque keys and encrypted binary data, not original filenames or MIME types.</p></article>
        <article><span>03 · DIRECT TRANSFERS</span><h3>WebRTC when peers can connect.</h3><p>Direct transfers send BlinkRoom AES-GCM ciphertext over a WebRTC DataChannel. BlinkRoom’s application and storage APIs do not receive file bytes in this mode; they relay signaling, and storage endpoints reject the upload.</p><small>WebRTC is not an anonymity system. Participants and network infrastructure—including a configured TURN relay—may observe transport metadata.</small></article>
        <article><span>04 · ENCRYPTION</span><h3>AES-GCM in participating browsers.</h3><p>A random 256-bit room key is generated by the creator’s browser. It lives after the # in the invite URL, is imported as a non-extractable browser CryptoKey, and is not placed in API requests, cookies, localStorage, or PostgreSQL.</p></article>
        <article><span>05 · ROOM LIFECYCLE</span><h3>Access ends before cleanup finishes.</h3><p>Rooms use a chosen 1, 6, 24, or 72-hour lifetime. Expiry, owner destruction, or the optional empty-room control makes the room inaccessible. Encrypted object and temporary metadata cleanup then runs asynchronously with retries.</p><small><b>Emergency access reset:</b> if a room code is exposed, the owner can rotate it and revoke previous access without destroying the room.</small></article>
        <article><span>06 · METADATA</span><h3>Operational data still exists.</h3><p>PostgreSQL stores room lifecycle state, opaque participant and item IDs, coarse item type, encrypted payloads/metadata, ciphertext sizes, timestamps, storage keys, presence, and upload state. Infrastructure can observe IP and network metadata.</p><small>BlinkRoom does not claim zero logs or complete anonymity.</small></article>
      </div>
    </section>
  </div>;
}

export function SecurityProcessPlayer({ expanded, onExpandedChange }: { expanded: boolean; onExpandedChange: (open: boolean) => void }) {
  const [scene, setScene] = useState(0);
  const [paused, setPaused] = useState(false);
  const [closed, setClosed] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);

  useEffect(() => {
    if (paused || closed || expanded || (!mobileOpen && window.matchMedia("(max-width: 720px)").matches)) return;
    const timer = window.setInterval(() => setScene((current) => (current + 1) % SCENE_COUNT), SCENE_MS);
    return () => window.clearInterval(timer);
  }, [paused, closed, expanded, mobileOpen]);
  useEffect(() => {
    if (!mobileOpen && !expanded) return;
    const previous = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const escape = (event: KeyboardEvent) => { if (event.key === "Escape") { onExpandedChange(false); setMobileOpen(false); } };
    document.addEventListener("keydown", escape);
    return () => { document.body.style.overflow = previous; document.removeEventListener("keydown", escape); };
  }, [mobileOpen, expanded, onExpandedChange]);

  if (closed) return null;
  return <>
    <button className="security-process-strip" onClick={() => setMobileOpen(true)}><i /><span>See how BlinkRoom protects your files</span><b>Watch 14s <ArrowRight /></b></button>
    <aside className={`security-process-player${mobileOpen ? " mobile-open" : ""}`} aria-label="BlinkRoom security process">
      <header><div><i /><span>BLINKROOM SECURITY</span></div><b>LIVE PROCESS</b><button onClick={() => { if (mobileOpen) setMobileOpen(false); else setClosed(true); }} aria-label="Close security process"><X /></button></header>
      <div className="security-process-stage" aria-live="off"><ProcessScene scene={scene} /></div>
      <div className="security-process-progress" aria-hidden="true"><i style={{ width: `${((scene + 1) / SCENE_COUNT) * 100}%` }} /></div>
      <footer><button onClick={() => setPaused((value) => !value)} aria-label={paused ? "Play security process" : "Pause security process"}>{paused ? <Play /> : <Pause />}</button><span>{scene + 1} / {SCENE_COUNT}</span><button className="security-explore" onClick={() => onExpandedChange(true)}>Explore security <Maximize2 /></button></footer>
    </aside>
    {expanded && <ArchitectureView onClose={() => onExpandedChange(false)} />}
  </>;
}
