import { SeoLanding } from "@/src/components/seo-landing";
import { seoMetadata } from "@/src/lib/seo";

export const metadata = seoMetadata(
  "/secure-file-sharing",
  "Secure File Sharing",
  "Securely share files through temporary, no-account rooms with browser-side encryption and instant drag-and-drop uploading.",
);

export default function Page() {
  return <SeoLanding path="/secure-file-sharing" eyebrow="SECURE FILE SHARING" title="Secure file sharing, without the usual friction." intro="Drop a file or open a temporary room, share one link, and keep files, images, text and links together for only as long as you need." proof="Temporary rooms · No account · Browser-side encryption" steps={[{ title: "Drop or create", text: "Drop valid files on the homepage for an instant room, or choose the room lifetime first." }, { title: "Share securely", text: "Stored file content and identifying metadata are encrypted in your browser before upload." }, { title: "Let access end", text: "The room expires after its selected lifetime, or its owner can destroy it sooner." }]} sections={[{ eyebrow: "BUILT FOR THE MOMENT", title: "A private space for what you need to share now.", paragraphs: ["BlinkRoom centers each exchange on a temporary room. Participants can revisit the same space while it remains active and see new items through realtime updates.", "There is no registration step. Create a room, drag and drop files, and send the complete room link through a channel you trust."], points: ["Instant homepage drag and drop", "Selectable 1, 6, 24 or 72-hour rooms", "Files, images, links and text in one room", "Owner-controlled early destruction"] }, { eyebrow: "SECURITY MODEL", title: "Encrypted before stored transfer.", paragraphs: ["For stored transfers, BlinkRoom encrypts file bytes and identifying metadata in the browser with AES-GCM. The room key is carried in the URL fragment, which browsers do not include in HTTP requests.", "Anyone with the complete room link may have what they need to enter and decrypt the room. Secure sharing still depends on sending that link only to intended recipients and keeping their devices protected."] }]} faqs={[{ question: "How does secure file sharing work in BlinkRoom?", answer: "Create a temporary room, add files and share the complete room link. Stored file content and identifying metadata are encrypted in the browser before upload." }, { question: "Can I share securely without an account?", answer: "Yes. BlinkRoom does not require registration to create or join a temporary room." }, { question: "Can I drag and drop files?", answer: "Yes. Dropping valid files on the homepage creates a room and starts the existing encrypted upload flow." }, { question: "How long does a secure room last?", answer: "You can choose 1, 6, 24 or 72 hours, or destroy the room earlier." }]} related={[{ href: "/encrypted-file-sharing", label: "Encrypted sharing" }, { href: "/private-file-sharing", label: "Private sharing" }, { href: "/temporary-file-sharing", label: "Temporary sharing" }]} />;
}
