import { NETWORK_CHUNK_BYTES, parseChunk, parseControl, serializeChunk, serializeControl, validateCompleteChunks, type TransferControl } from "./protocol";
import type { DirectFile, DirectReceive, DirectTransport, TransferProgress } from "./types";
import type { Socket } from "socket.io-client";

type Config = { iceServers: RTCIceServer[]; connectionTimeoutMs: number; maxDirectPeers: number };
type Peer = { pc: RTCPeerConnection; channel?: RTCDataChannel; open?: Promise<void>; resolveOpen?: () => void };
type Incoming = { from: string; itemId: string; type: "IMAGE" | "FILE"; encryptedMetadata: string; expectedSize: number; totalChunks: number; chunks: Map<number, BlobPart>; received: number };
type Callbacks = { onReceive(file: DirectReceive): void | Promise<void>; onProgress?(progress: TransferProgress): void; onError?(message: string): void };

export class WebRTCTransport implements DirectTransport {
  private peers = new Map<string, Peer>(); private incoming = new Map<string, Incoming>(); private ackWaiters = new Map<string, { resolve: () => void; reject: (error: Error) => void; acked: number; total: number; itemId: string }>(); private closed = false;
  constructor(private socket: Socket, private localId: string, private config: Config, private callbacks: Callbacks) { this.bind(); }
  setPeers(ids: string[]) { const wanted = new Set(ids.filter((id) => id !== this.localId).slice(0, this.config.maxDirectPeers)); for (const [id] of this.peers) if (!wanted.has(id)) this.drop(id); for (const id of wanted) if (!this.peers.has(id) && this.localId.localeCompare(id) < 0) void this.createPeer(id, true); }
  async sendFile(file: DirectFile, peerIds: string[], signal?: AbortSignal) { const delivered: string[] = [], failed: string[] = []; await Promise.all(peerIds.map(async (id) => { try { await this.sendTo(id, file, signal); delivered.push(id); } catch { failed.push(id); } })); return { delivered, failed }; }
  close() { this.closed = true; for (const [id] of this.peers) this.drop(id); for (const waiter of this.ackWaiters.values()) waiter.reject(new Error("Transfer closed")); this.ackWaiters.clear(); this.incoming.clear(); this.unbind(); }
  private async createPeer(id: string, initiator: boolean) { if (this.closed) throw new Error("Closed"); const pc = new RTCPeerConnection({ iceServers: this.config.iceServers }); const peer: Peer = { pc }; peer.open = new Promise<void>((resolve) => { peer.resolveOpen = resolve; }); this.peers.set(id, peer); pc.onicecandidate = ({ candidate }) => candidate && this.socket.emit("webrtc:ice-candidate", { target: id, candidate: candidate.toJSON() }); pc.onconnectionstatechange = () => { if (["failed", "closed"].includes(pc.connectionState)) { this.socket.emit("webrtc:failed", { target: id }); this.drop(id); } }; pc.ondatachannel = ({ channel }) => this.attachChannel(id, peer, channel); if (initiator) { this.attachChannel(id, peer, pc.createDataChannel("blinkroom-files", { ordered: true })); const description = await pc.createOffer(); await pc.setLocalDescription(description); this.socket.emit("webrtc:offer", { target: id, description: { type: description.type, sdp: description.sdp } }); } return peer; }
  private attachChannel(id: string, peer: Peer, channel: RTCDataChannel) { peer.channel = channel; channel.binaryType = "arraybuffer"; channel.bufferedAmountLowThreshold = 256 * 1024; channel.onopen = () => { peer.resolveOpen?.(); this.socket.emit("webrtc:ready", { target: id }); }; channel.onmessage = (event) => void this.handleMessage(id, event.data); channel.onclose = () => this.drop(id); }
  private async waitForPeer(id: string) { const peer = this.peers.get(id) ?? await this.createPeer(id, this.localId.localeCompare(id) < 0); if (peer.channel?.readyState === "open") return peer; await Promise.race([peer.open, new Promise((_, reject) => setTimeout(() => reject(new Error("Direct connection timeout")), this.config.connectionTimeoutMs))]); const channel = peer.channel as RTCDataChannel | undefined; if (!channel || channel.readyState !== "open") throw new Error("Direct channel unavailable"); return peer; }
  private async sendTo(id: string, file: DirectFile, signal?: AbortSignal) { const peer = await this.waitForPeer(id), channel = peer.channel!; const transferId = crypto.randomUUID(), totalChunks = Math.ceil(file.encrypted.size / NETWORK_CHUNK_BYTES); const start: TransferControl = { kind: "TRANSFER_START", version: 1, transferId, itemId: file.itemId, type: file.type, encryptedMetadata: file.encryptedMetadata, encryptedSize: file.encrypted.size, totalChunks }; channel.send(serializeControl(start)); const completion = new Promise<void>((resolve, reject) => this.ackWaiters.set(transferId, { resolve, reject, acked: 0, total: file.encrypted.size, itemId: file.itemId }));
    const abort = () => { if (channel.readyState === "open") channel.send(serializeControl({ kind: "TRANSFER_CANCEL", version: 1, transferId })); this.ackWaiters.get(transferId)?.reject(new Error("Cancelled")); this.ackWaiters.delete(transferId); }; signal?.addEventListener("abort", abort, { once: true });
    try { for (let index = 0; index < totalChunks; index++) { if (signal?.aborted || channel.readyState !== "open") throw new Error("Transfer interrupted"); await this.backpressure(channel); const chunk = await file.encrypted.slice(index * NETWORK_CHUNK_BYTES, Math.min(file.encrypted.size, (index + 1) * NETWORK_CHUNK_BYTES)).arrayBuffer(); channel.send(serializeChunk(transferId, index, chunk)); } channel.send(serializeControl({ kind: "TRANSFER_COMPLETE", version: 1, transferId })); await Promise.race([completion, new Promise((_, reject) => setTimeout(() => reject(new Error("Transfer acknowledgement timeout")), this.config.connectionTimeoutMs * 3))]); } finally { signal?.removeEventListener("abort", abort); this.ackWaiters.delete(transferId); }
  }
  private async backpressure(channel: RTCDataChannel) { if (channel.bufferedAmount <= 1024 * 1024) return; await new Promise<void>((resolve, reject) => { const timeout = setTimeout(() => reject(new Error("Data channel stalled")), this.config.connectionTimeoutMs); channel.addEventListener("bufferedamountlow", () => { clearTimeout(timeout); resolve(); }, { once: true }); }); }
  private async handleMessage(from: string, data: unknown) { try { if (typeof data === "string") { const message = parseControl(data); if (!message) throw new Error("Invalid transfer message"); await this.handleControl(from, message); return; } const frame = parseChunk(data instanceof ArrayBuffer ? data : await (data as Blob).arrayBuffer()); const transfer = this.incoming.get(frame.transferId); if (!transfer || frame.index >= transfer.totalChunks || transfer.chunks.has(frame.index)) throw new Error("Unexpected transfer chunk"); transfer.chunks.set(frame.index, frame.bytes); transfer.received += frame.bytes.byteLength; const peer = this.peers.get(from); peer?.channel?.send(serializeControl({ kind: "TRANSFER_ACK", version: 1, transferId: frame.transferId, receivedBytes: Math.min(transfer.received, transfer.expectedSize - 1) })); this.callbacks.onProgress?.({ transferId: frame.transferId, itemId: transfer.itemId, direction: "receiving", progress: Math.min(99, Math.round(transfer.received / transfer.expectedSize * 100)) }); } catch (error) { this.callbacks.onError?.(error instanceof Error ? error.message : "Direct transfer failed"); }
  }
  private async handleControl(from: string, message: TransferControl) { if (message.kind === "TRANSFER_START") { if (message.totalChunks < 1 || message.totalChunks > 1_000_000 || message.encryptedSize < 1) throw new Error("Invalid transfer declaration"); this.incoming.set(message.transferId, { from, itemId: message.itemId, type: message.type, encryptedMetadata: message.encryptedMetadata, expectedSize: message.encryptedSize, totalChunks: message.totalChunks, chunks: new Map(), received: 0 }); return; } if (message.kind === "TRANSFER_ACK") { const waiter = this.ackWaiters.get(message.transferId); if (waiter) { waiter.acked = Math.max(waiter.acked, message.receivedBytes); this.callbacks.onProgress?.({ transferId: message.transferId, itemId: waiter.itemId, direction: "sending", progress: Math.min(100, Math.round(waiter.acked / waiter.total * 100)) }); if (waiter.acked === waiter.total) waiter.resolve(); } return; } if (message.kind === "TRANSFER_CANCEL" || message.kind === "TRANSFER_ERROR") { this.incoming.delete(message.transferId); this.ackWaiters.get(message.transferId)?.reject(new Error(message.kind === "TRANSFER_CANCEL" ? "Cancelled" : message.message)); return; } const transfer = this.incoming.get(message.transferId); if (!transfer) throw new Error("Unknown transfer"); const encrypted = validateCompleteChunks(transfer.chunks, transfer.totalChunks, transfer.expectedSize, transfer.received); this.incoming.delete(message.transferId); await this.callbacks.onReceive({ from: transfer.from, itemId: transfer.itemId, type: transfer.type, encryptedMetadata: transfer.encryptedMetadata, encrypted }); this.peers.get(from)?.channel?.send(serializeControl({ kind: "TRANSFER_ACK", version: 1, transferId: message.transferId, receivedBytes: transfer.received })); }
  private bind() { this.socket.on("webrtc:offer", this.offer); this.socket.on("webrtc:answer", this.answer); this.socket.on("webrtc:ice-candidate", this.candidate); this.socket.on("webrtc:failed", this.failed); }
  private unbind() { this.socket.off("webrtc:offer", this.offer); this.socket.off("webrtc:answer", this.answer); this.socket.off("webrtc:ice-candidate", this.candidate); this.socket.off("webrtc:failed", this.failed); }
  private offer = async ({ from, description }: { from: string; description: RTCSessionDescriptionInit }) => { try { const peer = this.peers.get(from) ?? await this.createPeer(from, false); await peer.pc.setRemoteDescription(description); const answer = await peer.pc.createAnswer(); await peer.pc.setLocalDescription(answer); this.socket.emit("webrtc:answer", { target: from, description: { type: answer.type, sdp: answer.sdp } }); } catch { this.drop(from); } };
  private answer = async ({ from, description }: { from: string; description: RTCSessionDescriptionInit }) => { try { await this.peers.get(from)?.pc.setRemoteDescription(description); } catch { this.drop(from); } };
  private candidate = async ({ from, candidate }: { from: string; candidate: RTCIceCandidateInit }) => { try { await this.peers.get(from)?.pc.addIceCandidate(candidate); } catch { this.drop(from); } };
  private failed = ({ from }: { from: string }) => this.drop(from);
  private drop(id: string) { const peer = this.peers.get(id); if (!peer) return; peer.channel?.close(); peer.pc.close(); this.peers.delete(id); }
}
